version: '2'
services:
  postgres:
    image: postgres:9.4
    container_name: brp_dev_pg
    environment:
      - POSTGRES_DB=brp_dev
    volumes:
        - /opt/apps/postgres/data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis
    image: redis:3.0.5
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    ports:
      - "5000:5000/udp"
    volumes:
      - ../../logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../../01-input.json:/usr/share/logstash/pipeline/logstash.conf
    restart: always
    command: bash -c "logstash -l /usr/share/logstash/config/testlog.txt -f /usr/share/logstash/pipeline/logstash.conf"

  ehb-service:
    image: 508852077039.dkr.ecr.us-east-1.amazonaws.com/dbhi/eig/ehb-service:dev
    container_name: ehb
    env_file: ../../ehb_settings.env
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_DB=ehb_dev
    ports:
      - "32783:8000"
    depends_on:
      - redis

  app:
    image: 508852077039.dkr.ecr.us-east-1.amazonaws.com/dbhi/eig/biorepo-portal:dev
    container_name: brp
    env_file: ../../settings.env
    ports:
      - "32782:8000"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:5000"
        tag: "brp-dev"
    command: ["/opt/app/bin/wait-for-it.sh", "127.0.0.1:5000", "--", "/opt/app/bin/run.sh"]

    external_links:
        - brp_dev_pg
        - redis
        - ehb-service:ehb

    restart: always
